# Work with json file type
1. read json(read_json)
2. To Json(to_json)
3. json Normalize

# Assignment - To check what type of data use in split method in json

In [2]:
data = '{"employee_name": "Sushil", "email": "sushil@gamil.com","profile": [{"title1":"AIML","title2":"Engineer"}]}'

In [4]:
import pandas as pd
from io import StringIO

In [8]:
type(data)
pd.read_json(StringIO(data))

  employee_name             email                                   profile
0        Sushil  sushil@gamil.com  {'title1': 'AIML', 'title2': 'Engineer'}

In [9]:
pd.read_json(StringIO(data),orient='records')  ## Usually focus on main data records

  employee_name             email                                   profile
0        Sushil  sushil@gamil.com  {'title1': 'AIML', 'title2': 'Engineer'}

In [10]:
pd.read_json(StringIO(data),orient='index')

                                                        0
employee_name                                      Sushil
email                                    sushil@gamil.com
profile        [{'title1': 'AIML', 'title2': 'Engineer'}]

In [11]:
pd.read_json(StringIO(data),orient='values')

  employee_name             email                                   profile
0        Sushil  sushil@gamil.com  {'title1': 'AIML', 'title2': 'Engineer'}

In [12]:
dataf = pd.DataFrame([['a','b'],['c','d']],
                     index=['row1','row2'],
                     columns=['col1','col2'])

In [13]:
dataf

     col1 col2
row1    a    b
row2    c    d

In [14]:
dataf.to_json()

'{"col1":{"row1":"a","row2":"c"},"col2":{"row1":"b","row2":"d"}}'

In [15]:
dataf.to_json(orient='index')

'{"row1":{"col1":"a","col2":"b"},"row2":{"col1":"c","col2":"d"}}'

In [16]:
dataf.to_json(orient='columns')

'{"col1":{"row1":"a","row2":"c"},"col2":{"row1":"b","row2":"d"}}'

In [17]:
dataf.to_json(orient='records')

'[{"col1":"a","col2":"b"},{"col1":"c","col2":"d"}]'

In [18]:
dataf.to_json(orient='split') # split the data into row ,columns and values form

'{"columns":["col1","col2"],"index":["row1","row2"],"data":[["a","b"],["c","d"]]}'

In [19]:
dataf.to_json(orient='table')

'{"schema":{"fields":[{"name":"index","type":"string"},{"name":"col1","type":"string"},{"name":"col2","type":"string"}],"primaryKey":["index"],"pandas_version":"1.4.0"},"data":[{"index":"row1","col1":"a","col2":"b"},{"index":"row2","col1":"c","col2":"d"}]}'

In [22]:
schema = '{"schema":{"fields":[{"name":"index","type":"string"},{"name":"col1","type":"string"},{"name":"col2","type":"string"}],"primaryKey":["index"],"pandas_version":"1.4.0"},"data":[{"index":"row1","col1":"a","col2":"b"},{"index":"row2","col1":"c","col2":"d"}]}'

In [25]:
pd.read_json(StringIO(schema),orient='table')

     col1 col2
row1    a    b
row2    c    d

In [29]:
df = pd.read_csv(r'C:\Users\sushi\Downloads\iris/iris.data',header=None)

In [30]:
df.head()

     0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [33]:
jdata = df.to_json(orient='index')  # we can easily save on mongoDB Database

In [36]:
type(jdata)
jdata

'{"0":{"0":5.1,"1":3.5,"2":1.4,"3":0.2,"4":"Iris-setosa"},"1":{"0":4.9,"1":3.0,"2":1.4,"3":0.2,"4":"Iris-setosa"},"2":{"0":4.7,"1":3.2,"2":1.3,"3":0.2,"4":"Iris-setosa"},"3":{"0":4.6,"1":3.1,"2":1.5,"3":0.2,"4":"Iris-setosa"},"4":{"0":5.0,"1":3.6,"2":1.4,"3":0.2,"4":"Iris-setosa"},"5":{"0":5.4,"1":3.9,"2":1.7,"3":0.4,"4":"Iris-setosa"},"6":{"0":4.6,"1":3.4,"2":1.4,"3":0.3,"4":"Iris-setosa"},"7":{"0":5.0,"1":3.4,"2":1.5,"3":0.2,"4":"Iris-setosa"},"8":{"0":4.4,"1":2.9,"2":1.4,"3":0.2,"4":"Iris-setosa"},"9":{"0":4.9,"1":3.1,"2":1.5,"3":0.1,"4":"Iris-setosa"},"10":{"0":5.4,"1":3.7,"2":1.5,"3":0.2,"4":"Iris-setosa"},"11":{"0":4.8,"1":3.4,"2":1.6,"3":0.2,"4":"Iris-setosa"},"12":{"0":4.8,"1":3.0,"2":1.4,"3":0.1,"4":"Iris-setosa"},"13":{"0":4.3,"1":3.0,"2":1.1,"3":0.1,"4":"Iris-setosa"},"14":{"0":5.8,"1":4.0,"2":1.2,"3":0.2,"4":"Iris-setosa"},"15":{"0":5.7,"1":4.4,"2":1.5,"3":0.4,"4":"Iris-setosa"},"16":{"0":5.4,"1":3.9,"2":1.3,"3":0.4,"4":"Iris-setosa"},"17":{"0":5.1,"1":3.5,"2":1.4,"3":0.3,"4":"Iris-setosa"},"18":{"0":5.7,"1":3.8,"2":1.7,"3":0.3,"4":"Iris-setosa"},"19":{"0":5.1,"1":3.8,"2":1.5,"3":0.3,"4":"Iris-setosa"},"20":{"0":5.4,"1":3.4,"2":1.7,"3":0.2,"4":"Iris-setosa"},"21":{"0":5.1,"1":3.7,"2":1.5,"3":0.4,"4":"Iris-setosa"},"22":{"0":4.6,"1":3.6,"2":1.0,"3":0.2,"4":"Iris-setosa"},"23":{"0":5.1,"1":3.3,"2":1.7,"3":0.5,"4":"Iris-setosa"},"24":{"0":4.8,"1":3.4,"2":1.9,"3":0.2,"4":"Iris-setosa"},"25":{"0":5.0,"1":3.0,"2":1.6,"3":0.2,"4":"Iris-setosa"},"26":{"0":5.0,"1":3.4,"2":1.6,"3":0.4,"4":"Iris-setosa"},"27":{"0":5.2,"1":3.5,"2":1.5,"3":0.2,"4":"Iris-setosa"},"28":{"0":5.2,"1":3.4,"2":1.4,"3":0.2,"4":"Iris-setosa"},"29":{"0":4.7,"1":3.2,"2":1.6,"3":0.2,"4":"Iris-setosa"},"30":{"0":4.8,"1":3.1,"2":1.6,"3":0.2,"4":"Iris-setosa"},"31":{"0":5.4,"1":3.4,"2":1.5,"3":0.4,"4":"Iris-setosa"},"32":{"0":5.2,"1":4.1,"2":1.5,"3":0.1,"4":"Iris-setosa"},"33":{"0":5.5,"1":4.2,"2":1.4,"3":0.2,"4":"Iris-setosa"},"34":{"0":4.9,"1":3.1,"2":1.5,"3":0.1,"4":"Iris-setosa"},"35":{"0":5.0,"1":3.2,"2":1.2,"3":0.2,"4":"Iris-setosa"},"36":{"0":5.5,"1":3.5,"2":1.3,"3":0.2,"4":"Iris-setosa"},"37":{"0":4.9,"1":3.1,"2":1.5,"3":0.1,"4":"Iris-setosa"},"38":{"0":4.4,"1":3.0,"2":1.3,"3":0.2,"4":"Iris-setosa"},"39":{"0":5.1,"1":3.4,"2":1.5,"3":0.2,"4":"Iris-setosa"},"40":{"0":5.0,"1":3.5,"2":1.3,"3":0.3,"4":"Iris-setosa"},"41":{"0":4.5,"1":2.3,"2":1.3,"3":0.3,"4":"Iris-setosa"},"42":{"0":4.4,"1":3.2,"2":1.3,"3":0.2,"4":"Iris-setosa"},"43":{"0":5.0,"1":3.5,"2":1.6,"3":0.6,"4":"Iris-setosa"},"44":{"0":5.1,"1":3.8,"2":1.9,"3":0.4,"4":"Iris-setosa"},"45":{"0":4.8,"1":3.0,"2":1.4,"3":0.3,"4":"Iris-setosa"},"46":{"0":5.1,"1":3.8,"2":1.6,"3":0.2,"4":"Iris-setosa"},"47":{"0":4.6,"1":3.2,"2":1.4,"3":0.2,"4":"Iris-setosa"},"48":{"0":5.3,"1":3.7,"2":1.5,"3":0.2,"4":"Iris-setosa"},"49":{"0":5.0,"1":3.3,"2":1.4,"3":0.2,"4":"Iris-setosa"},"50":{"0":7.0,"1":3.2,"2":4.7,"3":1.4,"4":"Iris-versicolor"},"51":{"0":6.4,"1":3.2,"2":4.5,"3":1.5,"4":"Iris-versicolor"},"52":{"0":6.9,"1":3.1,"2":4.9,"3":1.5,"4":"Iris-versicolor"},"53":{"0":5.5,"1":2.3,"2":4.0,"3":1.3,"4":"Iris-versicolor"},"54":{"0":6.5,"1":2.8,"2":4.6,"3":1.5,"4":"Iris-versicolor"},"55":{"0":5.7,"1":2.8,"2":4.5,"3":1.3,"4":"Iris-versicolor"},"56":{"0":6.3,"1":3.3,"2":4.7,"3":1.6,"4":"Iris-versicolor"},"57":{"0":4.9,"1":2.4,"2":3.3,"3":1.0,"4":"Iris-versicolor"},"58":{"0":6.6,"1":2.9,"2":4.6,"3":1.3,"4":"Iris-versicolor"},"59":{"0":5.2,"1":2.7,"2":3.9,"3":1.4,"4":"Iris-versicolor"},"60":{"0":5.0,"1":2.0,"2":3.5,"3":1.0,"4":"Iris-versicolor"},"61":{"0":5.9,"1":3.0,"2":4.2,"3":1.5,"4":"Iris-versicolor"},"62":{"0":6.0,"1":2.2,"2":4.0,"3":1.0,"4":"Iris-versicolor"},"63":{"0":6.1,"1":2.9,"2":4.7,"3":1.4,"4":"Iris-versicolor"},"64":{"0":5.6,"1":2.9,"2":3.6,"3":1.3,"4":"Iris-versicolor"},"65":{"0":6.7,"1":3.1,"2":4.4,"3":1.4,"4":"Iris-versicolor"},"66":{"0":5.6,"1":3.0,"2":4.5,"3":1.5,"4":"Iris-versicolor"},"67":{"0":5.8,"1":2.7,"2":4.1,"3":1.0,"4":"Iris-versicolor"},"68":{"0":6.2,"1":2.2,"2":4.5,"3":1.5,"4":"Iris-versicolor"},"69":{"0":5.6,"1":2.5,"2":3.9,"3":1.1,"4":"Iris-versicolor"},"70":{"0":5.9,"1":3.2,"2":4.8,"3":1.8,"4":"Iris-versicolor"},"71":{"0":6.1,"1":2.8,"2":4.0,"3":1.3,"4":"Iris-versicolor"},"72":{"0":6.3,"1":2.5,"2":4.9,"3":1.5,"4":"Iris-versicolor"},"73":{"0":6.1,"1":2.8,"2":4.7,"3":1.2,"4":"Iris-versicolor"},"74":{"0":6.4,"1":2.9,"2":4.3,"3":1.3,"4":"Iris-versicolor"},"75":{"0":6.6,"1":3.0,"2":4.4,"3":1.4,"4":"Iris-versicolor"},"76":{"0":6.8,"1":2.8,"2":4.8,"3":1.4,"4":"Iris-versicolor"},"77":{"0":6.7,"1":3.0,"2":5.0,"3":1.7,"4":"Iris-versicolor"},"78":{"0":6.0,"1":2.9,"2":4.5,"3":1.5,"4":"Iris-versicolor"},"79":{"0":5.7,"1":2.6,"2":3.5,"3":1.0,"4":"Iris-versicolor"},"80":{"0":5.5,"1":2.4,"2":3.8,"3":1.1,"4":"Iris-versicolor"},"81":{"0":5.5,"1":2.4,"2":3.7,"3":1.0,"4":"Iris-versicolor"},"82":{"0":5.8,"1":2.7,"2":3.9,"3":1.2,"4":"Iris-versicolor"},"83":{"0":6.0,"1":2.7,"2":5.1,"3":1.6,"4":"Iris-versicolor"},"84":{"0":5.4,"1":3.0,"2":4.5,"3":1.5,"4":"Iris-versicolor"},"85":{"0":6.0,"1":3.4,"2":4.5,"3":1.6,"4":"Iris-versicolor"},"86":{"0":6.7,"1":3.1,"2":4.7,"3":1.5,"4":"Iris-versicolor"},"87":{"0":6.3,"1":2.3,"2":4.4,"3":1.3,"4":"Iris-versicolor"},"88":{"0":5.6,"1":3.0,"2":4.1,"3":1.3,"4":"Iris-versicolor"},"89":{"0":5.5,"1":2.5,"2":4.0,"3":1.3,"4":"Iris-versicolor"},"90":{"0":5.5,"1":2.6,"2":4.4,"3":1.2,"4":"Iris-versicolor"},"91":{"0":6.1,"1":3.0,"2":4.6,"3":1.4,"4":"Iris-versicolor"},"92":{"0":5.8,"1":2.6,"2":4.0,"3":1.2,"4":"Iris-versicolor"},"93":{"0":5.0,"1":2.3,"2":3.3,"3":1.0,"4":"Iris-versicolor"},"94":{"0":5.6,"1":2.7,"2":4.2,"3":1.3,"4":"Iris-versicolor"},"95":{"0":5.7,"1":3.0,"2":4.2,"3":1.2,"4":"Iris-versicolor"},"96":{"0":5.7,"1":2.9,"2":4.2,"3":1.3,"4":"Iris-versicolor"},"97":{"0":6.2,"1":2.9,"2":4.3,"3":1.3,"4":"Iris-versicolor"},"98":{"0":5.1,"1":2.5,"2":3.0,"3":1.1,"4":"Iris-versicolor"},"99":{"0":5.7,"1":2.8,"2":4.1,"3":1.3,"4":"Iris-versicolor"},"100":{"0":6.3,"1":3.3,"2":6.0,"3":2.5,"4":"Iris-virginica"},"101":{"0":5.8,"1":2.7,"2":5.1,"3":1.9,"4":"Iris-virginica"},"102":{"0":7.1,"1":3.0,"2":5.9,"3":2.1,"4":"Iris-virginica"},"103":{"0":6.3,"1":2.9,"2":5.6,"3":1.8,"4":"Iris-virginica"},"104":{"0":6.5,"1":3.0,"2":5.8,"3":2.2,"4":"Iris-virginica"},"105":{"0":7.6,"1":3.0,"2":6.6,"3":2.1,"4":"Iris-virginica"},"106":{"0":4.9,"1":2.5,"2":4.5,"3":1.7,"4":"Iris-virginica"},"107":{"0":7.3,"1":2.9,"2":6.3,"3":1.8,"4":"Iris-virginica"},"108":{"0":6.7,"1":2.5,"2":5.8,"3":1.8,"4":"Iris-virginica"},"109":{"0":7.2,"1":3.6,"2":6.1,"3":2.5,"4":"Iris-virginica"},"110":{"0":6.5,"1":3.2,"2":5.1,"3":2.0,"4":"Iris-virginica"},"111":{"0":6.4,"1":2.7,"2":5.3,"3":1.9,"4":"Iris-virginica"},"112":{"0":6.8,"1":3.0,"2":5.5,"3":2.1,"4":"Iris-virginica"},"113":{"0":5.7,"1":2.5,"2":5.0,"3":2.0,"4":"Iris-virginica"},"114":{"0":5.8,"1":2.8,"2":5.1,"3":2.4,"4":"Iris-virginica"},"115":{"0":6.4,"1":3.2,"2":5.3,"3":2.3,"4":"Iris-virginica"},"116":{"0":6.5,"1":3.0,"2":5.5,"3":1.8,"4":"Iris-virginica"},"117":{"0":7.7,"1":3.8,"2":6.7,"3":2.2,"4":"Iris-virginica"},"118":{"0":7.7,"1":2.6,"2":6.9,"3":2.3,"4":"Iris-virginica"},"119":{"0":6.0,"1":2.2,"2":5.0,"3":1.5,"4":"Iris-virginica"},"120":{"0":6.9,"1":3.2,"2":5.7,"3":2.3,"4":"Iris-virginica"},"121":{"0":5.6,"1":2.8,"2":4.9,"3":2.0,"4":"Iris-virginica"},"122":{"0":7.7,"1":2.8,"2":6.7,"3":2.0,"4":"Iris-virginica"},"123":{"0":6.3,"1":2.7,"2":4.9,"3":1.8,"4":"Iris-virginica"},"124":{"0":6.7,"1":3.3,"2":5.7,"3":2.1,"4":"Iris-virginica"},"125":{"0":7.2,"1":3.2,"2":6.0,"3":1.8,"4":"Iris-virginica"},"126":{"0":6.2,"1":2.8,"2":4.8,"3":1.8,"4":"Iris-virginica"},"127":{"0":6.1,"1":3.0,"2":4.9,"3":1.8,"4":"Iris-virginica"},"128":{"0":6.4,"1":2.8,"2":5.6,"3":2.1,"4":"Iris-virginica"},"129":{"0":7.2,"1":3.0,"2":5.8,"3":1.6,"4":"Iris-virginica"},"130":{"0":7.4,"1":2.8,"2":6.1,"3":1.9,"4":"Iris-virginica"},"131":{"0":7.9,"1":3.8,"2":6.4,"3":2.0,"4":"Iris-virginica"},"132":{"0":6.4,"1":2.8,"2":5.6,"3":2.2,"4":"Iris-virginica"},"133":{"0":6.3,"1":2.8,"2":5.1,"3":1.5,"4":"Iris-virginica"},"134":{"0":6.1,"1":2.6,"2":5.6,"3":1.4,"4":"Iris-virginica"},"135":{"0":7.7,"1":3.0,"2":6.1,"3":2.3,"4":"Iris-virginica"},"136":{"0":6.3,"1":3.4,"2":5.6,"3":2.4,"4":"Iris-virginica"},"137":{"0":6.4,"1":3.1,"2":5.5,"3":1.8,"4":"Iris-virginica"},"138":{"0":6.0,"1":3.0,"2":4.8,"3":1.8,"4":"Iris-virginica"},"139":{"0":6.9,"1":3.1,"2":5.4,"3":2.1,"4":"Iris-virginica"},"140":{"0":6.7,"1":3.1,"2":5.6,"3":2.4,"4":"Iris-virginica"},"141":{"0":6.9,"1":3.1,"2":5.1,"3":2.3,"4":"Iris-virginica"},"142":{"0":5.8,"1":2.7,"2":5.1,"3":1.9,"4":"Iris-virginica"},"143":{"0":6.8,"1":3.2,"2":5.9,"3":2.3,"4":"Iris-virginica"},"144":{"0":6.7,"1":3.3,"2":5.7,"3":2.5,"4":"Iris-virginica"},"145":{"0":6.7,"1":3.0,"2":5.2,"3":2.3,"4":"Iris-virginica"},"146":{"0":6.3,"1":2.5,"2":5.0,"3":1.9,"4":"Iris-virginica"},"147":{"0":6.5,"1":3.0,"2":5.2,"3":2.0,"4":"Iris-virginica"},"148":{"0":6.2,"1":3.4,"2":5.4,"3":2.3,"4":"Iris-virginica"},"149":{"0":5.9,"1":3.0,"2":5.1,"3":1.8,"4":"Iris-virginica"}}'

In [38]:
pd.read_json(StringIO(jdata),orient='index')

       0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [42]:
data = [{"employee_name": "Sushil", "email": "sushil@gamil.com","profile": {"title1":"AIML","title2":"Engineer"}}]

In [40]:
type(data)

list

In [46]:
pd.json_normalize(data)   #This is split the nested data inside the dictionary

  employee_name             email profile.title1 profile.title2
0        Sushil  sushil@gamil.com           AIML       Engineer

In [6]:
data = [
    {
        "state": "Utter Pradesh",
        "shortname": "UP",
        "info": {"Governor":"Rick Scott"},
        "counties": [
            {"name": "Dade", "population":1223},
            {"name": "Broward","population":2345},
            {"name": "Palm Beach","population":57987},
        ],
    },
    {
        "state": "Bangladesh",
        "shortname": "Bl",
        "info": {"Governor":"MileStone"},
        "counties": [
            {"name": "Goa Beach", "population":1523},
            {"name": "Tajmahal","population":835},
            {"name": "India Gate","population":5857},
        ],
    },
]

In [48]:
pd.json_normalize(data)

,state,shortname,countries,info.Governor
0,Utter Pradesh,UP,"[{'name': 'Dade', 'Population': 1223}, {'name'...",Rick Scott
1,Bangladesh,Bl,"[{'name': 'Austrilia', 'Population': 1523}, {'...",MileStone

In [13]:
pd.json_normalize(data, "counties", ["state","shortname"])

         name  population          state shortname
0        Dade        1223  Utter Pradesh        UP
1     Broward        2345  Utter Pradesh        UP
2  Palm Beach       57987  Utter Pradesh        UP
3   Goa Beach        1523     Bangladesh        Bl
4    Tajmahal         835     Bangladesh        Bl
5  India Gate        5857     Bangladesh        Bl

In [2]:
import pandas as pd

In [7]:
type(data)

list

In [16]:
pd

         name  population          state shortname
0        Dade        1223  Utter Pradesh        UP
1     Broward        2345  Utter Pradesh        UP
2  Palm Beach       57987  Utter Pradesh        UP
3   Goa Beach        1523     Bangladesh        Bl
4    Tajmahal         835     Bangladesh        Bl
5  India Gate        5857     Bangladesh        Bl