# pandas libraries
1. pandas dataframe
2. pandas series
3. pandas basic operations

In [2]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\sushi\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\sushi\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sushi\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sushi\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sushi\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\sushi\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [18]:
import pandas as pd
import numpy as np

In [15]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
## dataframe creation Read data in table form
tb_data = pd.DataFrame(data = np.arange(0,10).reshape(2,5),index = ["row1", "row2"],
             columns = ["column1","column2", "column3", "column4","column5"])

In [23]:
tb_data.head()   # show 5 record of head by default

      column1  column2  column3  column4  column5
row1        0        1        2        3        4
row2        5        6        7        8        9

In [26]:
tb_data.tail(1)   # show 5 record of tail by default

      column1  column2  column3  column4  column5
row2        5        6        7        8        9

In [28]:
type(tb_data)

pandas.core.frame.DataFrame

In [29]:
tb_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, row1 to row2
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   column1  2 non-null      int64
 1   column2  2 non-null      int64
 2   column3  2 non-null      int64
 3   column4  2 non-null      int64
 4   column5  2 non-null      int64
dtypes: int64(5)
memory usage: 96.0+ bytes

In [30]:
tb_data.describe()

        column1   column2   column3   column4   column5
count  2.000000  2.000000  2.000000  2.000000  2.000000
mean   2.500000  3.500000  4.500000  5.500000  6.500000
std    3.535534  3.535534  3.535534  3.535534  3.535534
min    0.000000  1.000000  2.000000  3.000000  4.000000
25%    1.250000  2.250000  3.250000  4.250000  5.250000
50%    2.500000  3.500000  4.500000  5.500000  6.500000
75%    3.750000  4.750000  5.750000  6.750000  7.750000
max    5.000000  6.000000  7.000000  8.000000  9.000000

In [31]:
## indexing
## 1. columnname wise, rowindex[loc], rowindex columnindex number[.iloc]

tb_data.head()

      column1  column2  column3  column4  column5
row1        0        1        2        3        4
row2        5        6        7        8        9

In [33]:
tb_data[['column1', 'column2', 'column3']]

      column1  column2  column3
row1        0        1        2
row2        5        6        7

In [46]:
one_col = tb_data['column4']  # in series only one row 
print(one_col)
type(one_col)

row1    3
row2    8
Name: column4, dtype: int64

pandas.core.series.Series

In [48]:
tb_data.loc['row1']

column1    0
column2    1
column3    2
column4    3
column5    4
Name: row1, dtype: int64

In [50]:
## loc method 
tb_data.loc[['row1','row2']]  # data frame

      column1  column2  column3  column4  column5
row1        0        1        2        3        4
row2        5        6        7        8        9

In [55]:
## rowindex and columnindex
tb_data.iloc[0:2,1:5]

      column2  column3  column4  column5
row1        1        2        3        4
row2        6        7        8        9

In [60]:
tb_data.iloc[0:2,0:5]

      column1  column2  column3  column4  column5
row1        0        1        2        3        4
row2        5        6        7        8        9

In [62]:
## convert dataframe into array values
tb_data.iloc[:,1:].values

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [63]:
#  basic opertions 
tb_data.isnull().sum()

column1    0
column2    0
column3    0
column4    0
column5    0
dtype: int64

In [64]:
tb_data = pd.DataFrame(data =[[1,2,np.nan],[2,4,6]], index = ["row1", "row2"],
             columns = ["column1","column2", "column3"])

In [65]:
tb_data

      column1  column2  column3
row1        1        2      NaN
row2        2        4      6.0

In [66]:
tb_data.isnull().sum() # count the non value

column1    0
column2    0
column3    1
dtype: int64

In [68]:
tb_data.isnull().sum()==0   # check what column values is non

column1     True
column2     True
column3    False
dtype: bool

In [74]:
tb_data['column1'].value_counts()

column1
1    1
2    1
Name: count, dtype: int64

In [72]:
tb_data['column2'].unique()

array([2, 4])

In [81]:
tb_data[tb_data['column2']>1]

      column1  column2  column3
row1        1        2      NaN
row2        2        4      6.0