# There Are some kind of method that Help to create DataFrame in Python

In [2]:
import pandas as pd

In [3]:
# this is dictionary format
df = pd.DataFrame({'days':['mon','Tus','Wed','Thur'],
                  'temprature':[28,27,25,20],
                  'events':['Rain','Cloud','Normal','Cold'],
                  'windSpeed':[8,7,9,10]})

In [4]:
df

   days  temprature  events  windSpeed
0   mon          28    Rain          8
1   Tus          27   Cloud          7
2   Wed          25  Normal          9
3  Thur          20    Cold         10

In [5]:
# this is list format in pandas
df = pd.DataFrame([('mon',29,'Rain',8),
                    ('Tus',30,'cloud',9),
                    ('Wed',31,'Sunny',10)])

In [6]:
df

     0   1      2   3
0  mon  29   Rain   8
1  Tus  30  cloud   9
2  Wed  31  Sunny  10

In [14]:
df = pd.DataFrame([{'days':'Mon','Temperature':30,'events':'Rainy','windSpeed':11},
                  {'days':'Tus','Temperature':29,'events':'Cloud'},
                  {'days':'wed','Temperature':26,'events':'Cloud'}])

In [15]:
df

  days  Temperature events  windSpeed
0  Mon           30  Rainy       11.0
1  Tus           29  Cloud        NaN
2  wed           26  Cloud        NaN